### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by JonathanAMichaels** [OlivierCodol/MotorNet#1]
General:
- [x] add license
- [x] add readme
- [x] remove playgrounds from master
- [x] add tutorials
- [x] Prune tasks module
- [x] make several losses per state possible
- [ ] Sort out and remove TODOs across all script files
- [x] remove the playground directories from the repo

Better visualization:
- [x] Expose all relevant variables from controller during training (inputs, outputs, plant, hidden states, costs, weights)
- [x] Plot those variables in a reasonable way

Experiment with cost optimization:
- [x] Externalize and report regularization costs
- [x] Muscle activation cost
- [x] Add activity cost (This is actually quite tricky since it's not implemented in GRUCell. I have to build my own cost based on the activations of each forward pass)

Expand toolbox functionality (important):
- [x] Add noise:
    - [x] To hidden units
    - [x] To inputs
    - [x] To feedback signals
- [ ] Multi-target movements with go cue
- [x] Allow perturbations to plant (shoulder/elbow) as a separate input signal
- [x] Add delays at all levels:
    - [x] Input delay (easy)
    - [x] Plant to kinematics delay (might already be well captured by the activation dynamics we're using now)
    - [x] Proprioceptive / visual hand position feedback delays (~40ms / ~90ms)

Expand toolbox functionality (longer-term):
- [ ] add compartments functionality
    - [ ] Add compartments to controller model
    - [ ] Allow sparse connectivity between compartments
    - [ ] Neural delay between compartments
- [ ] Plant:
    - [ ] add pendulum skeleton
    - [ ] add DM muscle type
- [ ] add visual perturbations.
- [x] Allow updating of targets after the forward pass (targets needs to be a function called after the forward pass). This will allow for training costs such as 'zero error when inside a target'.
- [x] Allow updating of inputs throughout the forward pass (inputs needs to be a function of the forward pass at every timestep). This will allow for complex tasks such as 'show next target only once hand has been in current target for x time'.
